name: Stale workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '45 11 * * *'

jobs:
  stale:
    uses: donavanbecker/.github/.github/workflows/stale.yml@latest
    with:
      days-before-issue-stale: 15
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
